&lt;!DOCTYPE HTML&gt;
&lt;!--
	Highlights by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
--&gt;
&lt;html&gt;
	&lt;head&gt;
		&lt;title&gt;Highlights by HTML5 UP&lt;/title&gt;
		&lt;meta http-equiv="content-type" content="text/html; charset=utf-8" /&gt;
		&lt;meta name="description" content="" /&gt;
		&lt;meta name="keywords" content="" /&gt;
		&lt;!--[if lte IE 8]&gt;&lt;script src="css/ie/html5shiv.js"&gt;&lt;/script&gt;&lt;![endif]--&gt;
		&lt;script src="js/jquery.min.js"&gt;&lt;/script&gt;
		&lt;script src="js/jquery.scrollex.min.js"&gt;&lt;/script&gt;
		&lt;script src="js/jquery.scrolly.min.js"&gt;&lt;/script&gt;
		&lt;script src="js/skel.min.js"&gt;&lt;/script&gt;
		&lt;script src="js/init.js"&gt;&lt;/script&gt;
		&lt;noscript&gt;
			&lt;link rel="stylesheet" href="css/skel.css" /&gt;
			&lt;link rel="stylesheet" href="css/style.css" /&gt;
			&lt;link rel="stylesheet" href="css/style-xlarge.css" /&gt;
		&lt;/noscript&gt;
		&lt;!--[if lte IE 8]&gt;&lt;link rel="stylesheet" href="css/ie/v8.css" /&gt;&lt;![endif]--&gt;
		&lt;!--[if lte IE 9]&gt;&lt;link rel="stylesheet" href="css/ie/v9.css" /&gt;&lt;![endif]--&gt;
	&lt;/head&gt;
	&lt;body&gt;

		&lt;!-- Header --&gt;
			&lt;section id="header"&gt;
				&lt;header class="major"&gt;
					&lt;h1&gt;Highlights&lt;/h1&gt;
					&lt;p&gt;A fun little { responsive } single pager by &lt;a href="http://html5up.net"&gt;HTML5 UP&lt;/a&gt;&lt;/p&gt;
				&lt;/header&gt;
				&lt;div class="container"&gt;
					&lt;ul class="actions"&gt;
						&lt;li&gt;&lt;a href="#one" class="button special scrolly"&gt;Begin&lt;/a&gt;&lt;/li&gt;
					&lt;/ul&gt;
				&lt;/div&gt;
			&lt;/section&gt;

		&lt;!-- One --&gt;
			&lt;section id="one" class="main special"&gt;
				&lt;div class="container"&gt;
					&lt;span class="image fit primary"&gt;&lt;img src="images/pic01.jpg" alt="" /&gt;&lt;/span&gt;
					&lt;div class="content"&gt;
						&lt;header class="major"&gt;
							&lt;h2&gt;Who I am&lt;/h2&gt;
						&lt;/header&gt;
						&lt;p&gt;Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum.&lt;/p&gt;
					&lt;/div&gt;
					&lt;a href="#two" class="goto-next scrolly"&gt;Next&lt;/a&gt;
				&lt;/div&gt;
			&lt;/section&gt;

		&lt;!-- Two --&gt;
			&lt;section id="two" class="main special"&gt;
				&lt;div class="container"&gt;
					&lt;span class="image fit primary"&gt;&lt;img src="images/pic02.jpg" alt="" /&gt;&lt;/span&gt;
					&lt;div class="content"&gt;
						&lt;header class="major"&gt;
							&lt;h2&gt;Stuff I do&lt;/h2&gt;
						&lt;/header&gt;
						&lt;p&gt;Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet vulputate.&lt;/p&gt;
						&lt;ul class="icons-grid"&gt;
							&lt;li&gt;
								&lt;span class="icon major fa-camera-retro"&gt;&lt;/span&gt;
								&lt;h3&gt;Magna Etiam&lt;/h3&gt;
							&lt;/li&gt;
							&lt;li&gt;
								&lt;span class="icon major fa-pencil"&gt;&lt;/span&gt;
								&lt;h3&gt;Lorem Ipsum&lt;/h3&gt;
							&lt;/li&gt;
							&lt;li&gt;
								&lt;span class="icon major fa-code"&gt;&lt;/span&gt;
								&lt;h3&gt;Nulla Tempus&lt;/h3&gt;
							&lt;/li&gt;
							&lt;li&gt;
								&lt;span class="icon major fa-coffee"&gt;&lt;/span&gt;
								&lt;h3&gt;Sed Feugiat&lt;/h3&gt;
							&lt;/li&gt;
						&lt;/ul&gt;
					&lt;/div&gt;
					&lt;a href="#three" class="goto-next scrolly"&gt;Next&lt;/a&gt;
				&lt;/div&gt;
			&lt;/section&gt;

		&lt;!-- Three --&gt;
			&lt;section id="three" class="main special"&gt;
				&lt;div class="container"&gt;
					&lt;span class="image fit primary"&gt;&lt;img src="images/pic03.jpg" alt="" /&gt;&lt;/span&gt;
					&lt;div class="content"&gt;
						&lt;header class="major"&gt;
							&lt;h2&gt;One more thing&lt;/h2&gt;
						&lt;/header&gt;
						&lt;p&gt;Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum.&lt;/p&gt;
					&lt;/div&gt;
					&lt;a href="#footer" class="goto-next scrolly"&gt;Next&lt;/a&gt;
				&lt;/div&gt;
			&lt;/section&gt;

		&lt;!-- Four --&gt;
		&lt;!--
			&lt;section id="four" class="main"&gt;
				&lt;div class="container"&gt;
					&lt;div class="content"&gt;
						&lt;header class="major"&gt;
							&lt;h2&gt;Elements&lt;/h2&gt;
						&lt;/header&gt;
						&lt;section&gt;
							&lt;h4&gt;Text&lt;/h4&gt;
							&lt;p&gt;This is &lt;b&gt;bold&lt;/b&gt; and this is &lt;strong&gt;strong&lt;/strong&gt;. This is &lt;i&gt;italic&lt;/i&gt; and this is &lt;em&gt;emphasized&lt;/em&gt;.
							This is &lt;sup&gt;superscript&lt;/sup&gt; text and this is &lt;sub&gt;subscript&lt;/sub&gt; text.
							This is &lt;u&gt;underlined&lt;/u&gt; and this is code: &lt;code&gt;for (;;) { ... }&lt;/code&gt;. Finally, &lt;a href="#"&gt;this is a link&lt;/a&gt;.&lt;/p&gt;
							&lt;hr /&gt;
							&lt;header&gt;
								&lt;h4&gt;Heading with a Subtitle&lt;/h4&gt;
								&lt;p&gt;Lorem ipsum dolor sit amet nullam id egestas urna aliquam&lt;/p&gt;
							&lt;/header&gt;
							&lt;p&gt;Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.&lt;/p&gt;
							&lt;header&gt;
								&lt;h5&gt;Heading with a Subtitle&lt;/h5&gt;
								&lt;p&gt;Lorem ipsum dolor sit amet nullam id egestas urna aliquam&lt;/p&gt;
							&lt;/header&gt;
							&lt;p&gt;Nunc lacinia ante nunc ac lobortis. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus ornare mi ut ante amet placerat aliquet. Volutpat eu sed ante lacinia sapien lorem accumsan varius montes viverra nibh in adipiscing blandit tempus accumsan.&lt;/p&gt;
							&lt;hr /&gt;
							&lt;h2&gt;Heading Level 2&lt;/h2&gt;
							&lt;h3&gt;Heading Level 3&lt;/h3&gt;
							&lt;h4&gt;Heading Level 4&lt;/h4&gt;
							&lt;h5&gt;Heading Level 5&lt;/h5&gt;
							&lt;h6&gt;Heading Level 6&lt;/h6&gt;
							&lt;hr /&gt;
							&lt;h5&gt;Blockquote&lt;/h5&gt;
							&lt;blockquote&gt;Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan faucibus. Vestibulum ante ipsum primis in faucibus lorem ipsum dolor sit amet nullam adipiscing eu felis.&lt;/blockquote&gt;
							&lt;h5&gt;Preformatted&lt;/h5&gt;
							&lt;pre&gt;&lt;code&gt;i = 0;

while (!deck.isInOrder()) {
print 'Iteration ' + i;
deck.shuffle();
i++;
}

print 'It took ' + i + ' iterations to sort the deck.';&lt;/code&gt;&lt;/pre&gt;
						&lt;/section&gt;

						&lt;section&gt;
							&lt;h4&gt;Lists&lt;/h4&gt;
							&lt;div class="row"&gt;
								&lt;div class="6u 12u$(medium)"&gt;
									&lt;h5&gt;Unordered&lt;/h5&gt;
									&lt;ul&gt;
										&lt;li&gt;Dolor pulvinar etiam.&lt;/li&gt;
										&lt;li&gt;Sagittis adipiscing.&lt;/li&gt;
										&lt;li&gt;Felis enim feugiat.&lt;/li&gt;
									&lt;/ul&gt;
									&lt;h5&gt;Alternate&lt;/h5&gt;
									&lt;ul class="alt"&gt;
										&lt;li&gt;Dolor pulvinar etiam.&lt;/li&gt;
										&lt;li&gt;Sagittis adipiscing.&lt;/li&gt;
										&lt;li&gt;Felis enim feugiat.&lt;/li&gt;
									&lt;/ul&gt;
								&lt;/div&gt;
								&lt;div class="6u$ 12u(medium)"&gt;
									&lt;h5&gt;Ordered&lt;/h5&gt;
									&lt;ol&gt;
										&lt;li&gt;Dolor pulvinar etiam.&lt;/li&gt;
										&lt;li&gt;Etiam vel felis viverra.&lt;/li&gt;
										&lt;li&gt;Felis enim feugiat.&lt;/li&gt;
										&lt;li&gt;Dolor pulvinar etiam.&lt;/li&gt;
										&lt;li&gt;Etiam vel felis lorem.&lt;/li&gt;
										&lt;li&gt;Felis enim et feugiat.&lt;/li&gt;
									&lt;/ol&gt;
									&lt;h5&gt;Icons&lt;/h5&gt;
									&lt;ul class="icons"&gt;
										&lt;li&gt;&lt;a href="#" class="icon fa-twitter"&gt;&lt;span class="label"&gt;Twitter&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
										&lt;li&gt;&lt;a href="#" class="icon fa-facebook"&gt;&lt;span class="label"&gt;Facebook&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
										&lt;li&gt;&lt;a href="#" class="icon fa-instagram"&gt;&lt;span class="label"&gt;Instagram&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
										&lt;li&gt;&lt;a href="#" class="icon fa-github"&gt;&lt;span class="label"&gt;Github&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
									&lt;/ul&gt;
								&lt;/div&gt;
							&lt;/div&gt;
							&lt;h5&gt;Actions&lt;/h5&gt;
							&lt;ul class="actions"&gt;
								&lt;li&gt;&lt;a href="#" class="button special"&gt;Default&lt;/a&gt;&lt;/li&gt;
								&lt;li&gt;&lt;a href="#" class="button"&gt;Default&lt;/a&gt;&lt;/li&gt;
							&lt;/ul&gt;
							&lt;ul class="actions small"&gt;
								&lt;li&gt;&lt;a href="#" class="button special small"&gt;Small&lt;/a&gt;&lt;/li&gt;
								&lt;li&gt;&lt;a href="#" class="button small"&gt;Small&lt;/a&gt;&lt;/li&gt;
							&lt;/ul&gt;
							&lt;div class="row"&gt;
								&lt;div class="6u 12u$(small)"&gt;
									&lt;ul class="actions vertical"&gt;
										&lt;li&gt;&lt;a href="#" class="button special"&gt;Default&lt;/a&gt;&lt;/li&gt;
										&lt;li&gt;&lt;a href="#" class="button"&gt;Default&lt;/a&gt;&lt;/li&gt;
									&lt;/ul&gt;
								&lt;/div&gt;
								&lt;div class="6u$ 12u$(small)"&gt;
									&lt;ul class="actions vertical small"&gt;
										&lt;li&gt;&lt;a href="#" class="button special small"&gt;Small&lt;/a&gt;&lt;/li&gt;
										&lt;li&gt;&lt;a href="#" class="button small"&gt;Small&lt;/a&gt;&lt;/li&gt;
									&lt;/ul&gt;
								&lt;/div&gt;
								&lt;div class="6u 12u$(small)"&gt;
									&lt;ul class="actions vertical"&gt;
										&lt;li&gt;&lt;a href="#" class="button special fit"&gt;Default&lt;/a&gt;&lt;/li&gt;
										&lt;li&gt;&lt;a href="#" class="button fit"&gt;Default&lt;/a&gt;&lt;/li&gt;
									&lt;/ul&gt;
								&lt;/div&gt;
								&lt;div class="6u$ 12u$(small)"&gt;
									&lt;ul class="actions vertical small"&gt;
										&lt;li&gt;&lt;a href="#" class="button special small fit"&gt;Small&lt;/a&gt;&lt;/li&gt;
										&lt;li&gt;&lt;a href="#" class="button small fit"&gt;Small&lt;/a&gt;&lt;/li&gt;
									&lt;/ul&gt;
								&lt;/div&gt;
							&lt;/div&gt;
						&lt;/section&gt;

						&lt;section&gt;
							&lt;h4&gt;Table&lt;/h4&gt;
							&lt;h5&gt;Default&lt;/h5&gt;
							&lt;div class="table-wrapper"&gt;
								&lt;table&gt;
									&lt;thead&gt;
										&lt;tr&gt;
											&lt;th&gt;Name&lt;/th&gt;
											&lt;th&gt;Description&lt;/th&gt;
											&lt;th&gt;Price&lt;/th&gt;
										&lt;/tr&gt;
									&lt;/thead&gt;
									&lt;tbody&gt;
										&lt;tr&gt;
											&lt;td&gt;Item One&lt;/td&gt;
											&lt;td&gt;Ante turpis integer aliquet porttitor.&lt;/td&gt;
											&lt;td&gt;29.99&lt;/td&gt;
										&lt;/tr&gt;
										&lt;tr&gt;
											&lt;td&gt;Item Two&lt;/td&gt;
											&lt;td&gt;Vis ac commodo adipiscing arcu aliquet.&lt;/td&gt;
											&lt;td&gt;19.99&lt;/td&gt;
										&lt;/tr&gt;
										&lt;tr&gt;
											&lt;td&gt;Item Three&lt;/td&gt;
											&lt;td&gt; Morbi faucibus arcu accumsan lorem.&lt;/td&gt;
											&lt;td&gt;29.99&lt;/td&gt;
										&lt;/tr&gt;
										&lt;tr&gt;
											&lt;td&gt;Item Four&lt;/td&gt;
											&lt;td&gt;Vitae integer tempus condimentum.&lt;/td&gt;
											&lt;td&gt;19.99&lt;/td&gt;
										&lt;/tr&gt;
										&lt;tr&gt;
											&lt;td&gt;Item Five&lt;/td&gt;
											&lt;td&gt;Ante turpis integer aliquet porttitor.&lt;/td&gt;
											&lt;td&gt;29.99&lt;/td&gt;
										&lt;/tr&gt;
									&lt;/tbody&gt;
									&lt;tfoot&gt;
										&lt;tr&gt;
											&lt;td colspan="2"&gt;&lt;/td&gt;
											&lt;td&gt;100.00&lt;/td&gt;
										&lt;/tr&gt;
									&lt;/tfoot&gt;
								&lt;/table&gt;
							&lt;/div&gt;

							&lt;h5&gt;Alternate&lt;/h5&gt;
							&lt;div class="table-wrapper"&gt;
								&lt;table class="alt"&gt;
									&lt;thead&gt;
										&lt;tr&gt;
											&lt;th&gt;Name&lt;/th&gt;
											&lt;th&gt;Description&lt;/th&gt;
											&lt;th&gt;Price&lt;/th&gt;
										&lt;/tr&gt;
									&lt;/thead&gt;
									&lt;tbody&gt;
										&lt;tr&gt;
											&lt;td&gt;Item One&lt;/td&gt;
											&lt;td&gt;Ante turpis integer aliquet porttitor.&lt;/td&gt;
											&lt;td&gt;29.99&lt;/td&gt;
										&lt;/tr&gt;
										&lt;tr&gt;
											&lt;td&gt;Item Two&lt;/td&gt;
											&lt;td&gt;Vis ac commodo adipiscing arcu aliquet.&lt;/td&gt;
											&lt;td&gt;19.99&lt;/td&gt;
										&lt;/tr&gt;
										&lt;tr&gt;
											&lt;td&gt;Item Three&lt;/td&gt;
											&lt;td&gt; Morbi faucibus arcu accumsan lorem.&lt;/td&gt;
											&lt;td&gt;29.99&lt;/td&gt;
										&lt;/tr&gt;
										&lt;tr&gt;
											&lt;td&gt;Item Four&lt;/td&gt;
											&lt;td&gt;Vitae integer tempus condimentum.&lt;/td&gt;
											&lt;td&gt;19.99&lt;/td&gt;
										&lt;/tr&gt;
										&lt;tr&gt;
											&lt;td&gt;Item Five&lt;/td&gt;
											&lt;td&gt;Ante turpis integer aliquet porttitor.&lt;/td&gt;
											&lt;td&gt;29.99&lt;/td&gt;
										&lt;/tr&gt;
									&lt;/tbody&gt;
									&lt;tfoot&gt;
										&lt;tr&gt;
											&lt;td colspan="2"&gt;&lt;/td&gt;
											&lt;td&gt;100.00&lt;/td&gt;
										&lt;/tr&gt;
									&lt;/tfoot&gt;
								&lt;/table&gt;
							&lt;/div&gt;
						&lt;/section&gt;

						&lt;section&gt;
							&lt;h4&gt;Buttons&lt;/h4&gt;
							&lt;ul class="actions"&gt;
								&lt;li&gt;&lt;a href="#" class="button special"&gt;Special&lt;/a&gt;&lt;/li&gt;
								&lt;li&gt;&lt;a href="#" class="button"&gt;Default&lt;/a&gt;&lt;/li&gt;
							&lt;/ul&gt;
							&lt;ul class="actions"&gt;
								&lt;li&gt;&lt;a href="#" class="button"&gt;Default&lt;/a&gt;&lt;/li&gt;
								&lt;li&gt;&lt;a href="#" class="button small"&gt;Small&lt;/a&gt;&lt;/li&gt;
							&lt;/ul&gt;
							&lt;ul class="actions fit"&gt;
								&lt;li&gt;&lt;a href="#" class="button special fit"&gt;Fit&lt;/a&gt;&lt;/li&gt;
								&lt;li&gt;&lt;a href="#" class="button fit"&gt;Fit&lt;/a&gt;&lt;/li&gt;
							&lt;/ul&gt;
							&lt;ul class="actions fit small"&gt;
								&lt;li&gt;&lt;a href="#" class="button special fit small"&gt;Fit + Small&lt;/a&gt;&lt;/li&gt;
								&lt;li&gt;&lt;a href="#" class="button fit small"&gt;Fit + Small&lt;/a&gt;&lt;/li&gt;
							&lt;/ul&gt;
							&lt;ul class="actions"&gt;
								&lt;li&gt;&lt;a href="#" class="button special icon fa-download"&gt;Icon&lt;/a&gt;&lt;/li&gt;
								&lt;li&gt;&lt;a href="#" class="button icon fa-download"&gt;Icon&lt;/a&gt;&lt;/li&gt;
							&lt;/ul&gt;
							&lt;ul class="actions"&gt;
								&lt;li&gt;&lt;span class="button special disabled"&gt;Disabled&lt;/span&gt;&lt;/li&gt;
								&lt;li&gt;&lt;span class="button disabled"&gt;Disabled&lt;/span&gt;&lt;/li&gt;
							&lt;/ul&gt;
						&lt;/section&gt;

						&lt;section&gt;
							&lt;h4&gt;Form&lt;/h4&gt;
							&lt;form method="post" action="#"&gt;
								&lt;div class="row uniform"&gt;
									&lt;div class="6u 12u$(xsmall)"&gt;
										&lt;input type="text" name="demo-name" id="demo-name" value="" placeholder="Name" /&gt;
									&lt;/div&gt;
									&lt;div class="6u$ 12u$(xsmall)"&gt;
										&lt;input type="email" name="demo-email" id="demo-email" value="" placeholder="Email" /&gt;
									&lt;/div&gt;
									&lt;div class="12u$"&gt;
										&lt;div class="select-wrapper"&gt;
											&lt;select name="demo-category" id="demo-category"&gt;
												&lt;option value=""&gt;- Category -&lt;/option&gt;
												&lt;option value="1"&gt;Manufacturing&lt;/option&gt;
												&lt;option value="1"&gt;Shipping&lt;/option&gt;
												&lt;option value="1"&gt;Administration&lt;/option&gt;
												&lt;option value="1"&gt;Human Resources&lt;/option&gt;
											&lt;/select&gt;
										&lt;/div&gt;
									&lt;/div&gt;
									&lt;div class="4u 12u$(small)"&gt;
										&lt;input type="radio" id="demo-priority-low" name="demo-priority" checked&gt;
										&lt;label for="demo-priority-low"&gt;Low&lt;/label&gt;
									&lt;/div&gt;
									&lt;div class="4u 12u$(small)"&gt;
										&lt;input type="radio" id="demo-priority-normal" name="demo-priority"&gt;
										&lt;label for="demo-priority-normal"&gt;Normal&lt;/label&gt;
									&lt;/div&gt;
									&lt;div class="4u$ 12u$(small)"&gt;
										&lt;input type="radio" id="demo-priority-high" name="demo-priority"&gt;
										&lt;label for="demo-priority-high"&gt;High&lt;/label&gt;
									&lt;/div&gt;
									&lt;div class="6u 12u$(small)"&gt;
										&lt;input type="checkbox" id="demo-copy" name="demo-copy"&gt;
										&lt;label for="demo-copy"&gt;Email me a copy&lt;/label&gt;
									&lt;/div&gt;
									&lt;div class="6u$ 12u$(small)"&gt;
										&lt;input type="checkbox" id="demo-human" name="demo-human" checked&gt;
										&lt;label for="demo-human"&gt;Not a robot&lt;/label&gt;
									&lt;/div&gt;
									&lt;div class="12u$"&gt;
										&lt;textarea name="demo-message" id="demo-message" placeholder="Enter your message" rows="6"&gt;&lt;/textarea&gt;
									&lt;/div&gt;
									&lt;div class="12u$"&gt;
										&lt;ul class="actions"&gt;
											&lt;li&gt;&lt;input type="submit" value="Send Message" class="special" /&gt;&lt;/li&gt;
											&lt;li&gt;&lt;input type="reset" value="Reset" /&gt;&lt;/li&gt;
										&lt;/ul&gt;
									&lt;/div&gt;
								&lt;/div&gt;
							&lt;/form&gt;
						&lt;/section&gt;

						&lt;section&gt;
							&lt;h4&gt;Image&lt;/h4&gt;
							&lt;h5&gt;Fit&lt;/h5&gt;
							&lt;div class="box alt"&gt;
								&lt;div class="row uniform 50%"&gt;
									&lt;div class="12u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
									&lt;div class="4u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
									&lt;div class="4u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
									&lt;div class="4u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
									&lt;div class="4u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
									&lt;div class="4u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
									&lt;div class="4u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
									&lt;div class="4u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
									&lt;div class="4u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
									&lt;div class="4u"&gt;&lt;span class="image fit"&gt;&lt;img src="images/pic04.jpg" alt="" /&gt;&lt;/span&gt;&lt;/div&gt;
								&lt;/div&gt;
							&lt;/div&gt;
							&lt;h5&gt;Left &amp; Right&lt;/h5&gt;
							&lt;p&gt;&lt;span class="image left"&gt;&lt;img src="images/pic05.jpg" alt="" /&gt;&lt;/span&gt;Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent.&lt;/p&gt;
							&lt;p&gt;&lt;span class="image right"&gt;&lt;img src="images/pic05.jpg" alt="" /&gt;&lt;/span&gt;Fringilla nisl. Donec accumsan interdum nisi, quis tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent tincidunt felis sagittis eget. tempus euismod. Vestibulum ante ipsum primis in faucibus vestibulum. Blandit adipiscing eu felis iaculis volutpat ac adipiscing accumsan eu faucibus. Integer ac pellentesque praesent.&lt;/p&gt;
						&lt;/section&gt;

					&lt;/div&gt;
					&lt;a href="#footer" class="goto-next scrolly"&gt;Next&lt;/a&gt;
				&lt;/div&gt;
			&lt;/section&gt;
		--&gt;

		&lt;!-- Footer --&gt;
			&lt;section id="footer"&gt;
				&lt;div class="container"&gt;
					&lt;header class="major"&gt;
						&lt;h2&gt;Get in touch&lt;/h2&gt;
					&lt;/header&gt;
					&lt;form method="post" action="#"&gt;
						&lt;div class="row uniform"&gt;
							&lt;div class="6u 12u$(xsmall)"&gt;&lt;input type="text" name="name" id="name" placeholder="Name" /&gt;
							&lt;div class="6u$ 12u$(xsmall)"&gt;&lt;input type="email" name="email" id="email" placeholder="Email" /&gt;
							&lt;div class="12u$"&gt;&lt;textarea name="message" id="message" placeholder="Message" rows="4"&gt;&lt;/textarea&gt;&lt;/div&gt;
							&lt;div class="12u$"&gt;
								&lt;ul class="actions"&gt;
									&lt;li&gt;&lt;input type="submit" value="Send Message" class="special" /&gt;&lt;/li&gt;
								&lt;/ul&gt;
							&lt;/div&gt;
						&lt;/div&gt;
					&lt;/form&gt;
				&lt;/div&gt;
				&lt;footer&gt;
					&lt;ul class="icons"&gt;
						&lt;li&gt;&lt;a href="#" class="icon alt fa-twitter"&gt;&lt;span class="label"&gt;Twitter&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="#" class="icon alt fa-facebook"&gt;&lt;span class="label"&gt;Facebook&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="#" class="icon alt fa-instagram"&gt;&lt;span class="label"&gt;Instagram&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="#" class="icon alt fa-dribbble"&gt;&lt;span class="label"&gt;Dribbble&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
						&lt;li&gt;&lt;a href="#" class="icon alt fa-envelope"&gt;&lt;span class="label"&gt;Email&lt;/span&gt;&lt;/a&gt;&lt;/li&gt;
					&lt;/ul&gt;
					&lt;ul class="copyright"&gt;